name: Feature request
description: Something you'd like Moontors to do.
labels: [enhancement]
body:
  - type: textarea
    id: what
    attributes:
      label: What you'd like
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why it would help
